package io.github.techbellys.utility.bedrock.knowledgebase;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import software.amazon.awssdk.services.bedrockagentruntime.BedrockAgentRuntimeClient;
import software.amazon.awssdk.services.bedrockagentruntime.model.KnowledgeBaseRetrieveAndGenerateConfiguration;
import software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveAndGenerateConfiguration;
import software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveAndGenerateInput;
import software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveAndGenerateRequest;
import software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveAndGenerateResponse;
import software.amazon.awssdk.services.bedrockagentruntime.model.RetrieveAndGenerateType;

/**
 * Service class to handle operations related to the AWS Bedrock Knowledge Base.
 * Provides functionality to process queries using the Retrieve and Generate (RAG) approach.
 */
@Service
public class KnowledgeBase {

    private static final Logger logger = LoggerFactory.getLogger(KnowledgeBase.class);

    @Autowired
    private BedrockAgentRuntimeClient bedrockAgentRuntimeClient;

    /**
     * Processes a query using the specified Knowledge Base and model.
     *
     * @param modelId        The ARN of the model to be used.
     * @param knowledgeBaseId The ID of the Knowledge Base.
     * @param query          The query text to process.
     * @return The response text generated by the Knowledge Base.
     */
    public String process(String modelId, String knowledgeBaseId, String query) {
        return invokeModelWithRAG(modelId, knowledgeBaseId, query);
    }

    /**
     * Invokes the AWS Bedrock Knowledge Base with Retrieve and Generate (RAG) configuration.
     *
     * @param modelId        The ARN of the model to be used.
     * @param knowledgeBaseId The ID of the Knowledge Base.
     * @param query          The query text to process.
     * @return The response text generated by the Knowledge Base.
     */
    private String invokeModelWithRAG(String modelId, String knowledgeBaseId, String query) {
        try {
            // Configure Knowledge Base
            KnowledgeBaseRetrieveAndGenerateConfiguration kbConfig = KnowledgeBaseRetrieveAndGenerateConfiguration.builder()
                    .knowledgeBaseId(knowledgeBaseId)
                    .modelArn(modelId)
                    .build();

            RetrieveAndGenerateConfiguration config = RetrieveAndGenerateConfiguration.builder()
                    .knowledgeBaseConfiguration(kbConfig)
                    .type(RetrieveAndGenerateType.KNOWLEDGE_BASE)
                    .build();

            // Prepare input
            RetrieveAndGenerateInput input = RetrieveAndGenerateInput.builder().text(query).build();

            // Build request
            RetrieveAndGenerateRequest request = RetrieveAndGenerateRequest.builder()
                    .input(input)
                    .retrieveAndGenerateConfiguration(config)
                    .build();

            // Call AWS Bedrock Agent Runtime and get response
            RetrieveAndGenerateResponse response = bedrockAgentRuntimeClient.retrieveAndGenerate(request);

            // Return the generated response text
            return response.output().text();
        } catch (Exception e) {
            logger.error("Error during RAG invocation: {}", e.getMessage(), e);
            throw new RuntimeException("Failed to process query with RAG", e);
        }
    }
}
