package io.github.techbellys.utility.bedrock.service;

/**
 * Service interface for interacting with AWS Bedrock Agents.
 * Provides functionality to invoke an agent with a given prompt and retrieve its response.
 */
public interface BedrockAgentService {

    /**
     * Invokes an AWS Bedrock Agent with the specified parameters and retrieves its response.
     *
     * @param prompt       The input text to send to the agent.
     * @param agentId      The ID of the agent to invoke.
     * @param agentAliasId The alias ID of the agent.
     * @param sessionId    The session ID for maintaining agent context across multiple interactions.
     * @return The response text generated by the agent.
     */
    String invokeBedrockAgent(String prompt,
                              String agentId,
                              String agentAliasId,
                              String sessionId);
}
