package io.github.techbellys.utility.bedrock.service;

/**
 * Service interface for interacting with AWS Bedrock Knowledge Base.
 * Provides functionality to process user queries using Retrieve and Generate (RAG) methodology.
 */
public interface KnowledgeBaseService {

    /**
     * Processes the user query using the specified model and knowledge base via Bedrock Agent Runtime with RAG.
     *
     * @param modelId        The ID of the model to use for processing the query.
     * @param knowledgeBaseId The ID of the knowledge base to query.
     * @param query          The user query text to process.
     * @return The response text generated by the knowledge base.
     */
    String processQuery(String modelId, String knowledgeBaseId, String query);
}
