package io.github.techbellys.utility.bedrock.service.impl;

import io.github.techbellys.utility.bedrock.knowledgebase.KnowledgeBase;
import io.github.techbellys.utility.bedrock.service.KnowledgeBaseService;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Implementation of the {@link KnowledgeBaseService} interface.
 * Provides functionality to process queries using an AWS Bedrock Knowledge Base.
 */
public class KnowledgeBaseServiceImpl implements KnowledgeBaseService {

    @Autowired
    private KnowledgeBase knowledgeBase;

    /**
     * Processes a query using the specified model and knowledge base.
     *
     * @param modelId        The ID of the model to use for processing the query.
     * @param knowledgeBaseId The ID of the knowledge base to query.
     * @param query          The query text to be processed.
     * @return The response generated by the knowledge base.
     */
    @Override
    public String processQuery(String modelId, String knowledgeBaseId, String query) {
        return knowledgeBase.process(modelId, knowledgeBaseId, query);
    }
}
